### PR TITLE
Revamp with configurable keyword and option to open link

### PR DESCRIPTION
**Pull request by vitorgalvao**
Updated with [what we talked about on the forum](https://www.alfredforum.com/topic/19191-howdoi-instant-coding-answers/#comment-101011) and more. It does not show the answer inline, but it:

* Has a configurable keyword (defaults to `howdy`).
* Has a configuration to show as Large Type (as opposed to notification). On by default.
* Shows a dialog asking the user if they want to open the link where the answer came from.

[⤓ Packaged workflow](https://github.com/gleitz/alfred-howdoi/files/10502625/Howdoi.alfredworkflow.zip) for easier review.

### CODE REVIEW

**Comment by gleitz** [comment]
Awesome! Will take a look

**Comment by gleitz** [comment]
When I updated to this version, I get the following error output (`howdoi` executable cannot be found)

```
[10:12:09.582] Howdoi[Keyword] Processing complete
[10:12:09.586] Howdoi[Keyword] Passing output 'format date bash' to Run Script
[10:12:09.608] ERROR: Howdoi[Run Script] /Users/gleitz/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/76E38065-5E5E-4BE8-AA79-7C64C2D7D094: line 1: howdoi: command not found
[10:12:09.609] Howdoi[Run Script] Processing complete
[10:12:09.610] Howdoi[Run Script] Passing output '' to Conditional
[10:12:09.616] Howdoi[Conditional] Processing complete
[10:12:09.617] Howdoi[Conditional] Passing output '' to Large Type
[10:12:09.618] Howdoi[Run Script] Passing output '' to Copy to Clipboard
[10:12:09.618] Howdoi[Copy to Clipboard] Processing complete
[10:12:09.619] Howdoi[Copy to Clipboard] Passing output '' to Dialog Conditional
```

My `howdoi` executable is located at 

```
» which howdoi
/Users/gleitz/.homebrew/bin/howdoi
```

I'm wondering how Alfred is supposed to know about my Homebrew path? You mentioned `Alfred 5 itself includes the Homebrew locations in PATH, meaning the Configuration to set the path to the CLI can be removed.` I know the usual Homebrew path is `/usr/local/Cellar/`, but in this case I use a custom prefix. I was able to get that prefix using:

```
echo $HOMEBREW_PREFIX
/Users/gleitz/.homebrew
```

This is an issue that I ran into in the past and it's why the previous version had the user configure the path to their executable. It would be great if Alfred can add `$HOMEBREW_PREFIX` to the PATH automatically.

**Comment by vitorgalvao** [comment]
> I'm wondering how Alfred is supposed to know about my Homebrew path?

Alfred knows about the recommended paths, `/opt/homebrew/bin` and `/usr/local/bin`. [Homebrew itself **highly discourages** installing outside the default prefixes](https://docs.brew.sh/Installation#untar-anywhere-unsupported), to the point that if you have a Homebrew issue and your installation path is not one of the defaults, you won’t get support on the Homebrew repos. As such, those are what Alfred supports. It’s also what the vast majority of workflows do, and what [the dependencies feature](https://www.alfredapp.com/help/kb/dependencies/) uses.

> It would be great if Alfred can add `$HOMEBREW_PREFIX` to the PATH automatically.

There is no good way for Alfred (or any external tool) to know that variable. Your terminal session knows it because your shell’s startup files have it in. [But Alfred does not load your shell’s startup files](https://www.alfredapp.com/help/workflows/advanced/understanding-scripting-environment/), everyone’s environment is different. In other words, `HOMEBREW_PREFIX` is not a global state, but a local one which is highly dependent on your shell.

What you can do is add a [Workflow Environment Variable](https://www.alfredapp.com/help/workflows/advanced/variables/#environment) consisting of setting `PATH` to `/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/gleitz/.homebrew`. That way it extends Alfred’s own `PATH` to include your custom installation.

**Comment by gleitz** [comment]
I wanted to go ahead and test the rest of the functionality, so I changed all instances of `howdoi` to `/Users/gleitz/.homebrew/bin/howdoi`. I will test your recommendation of setting the `Workflow Environment Variable`.

Love the large type. I think that's better than a notification which you usually can't read because it doesn't show enough text.

When it comes to getting a URL, the command needs to be `howdoi --link {var:question_keyword}` (passing the original question) rather than `"${1}"` (which is the answer output from the previous step). When I made that change, the URL opens properly.

One of the best parts of howdoi is that it keeps you from having to open your browser. You ask a question, you get an answer (large type and on your clipboard) and you can paste to stay right in your editor. I think the answer to "do you want to open URL?" will usually (~90% of the time) be no. It may be nice to have that optional occasionally.

I'm thinking we can do the following:

`howdoi format date bash` -> gives an answer -> large type -> copy to clipboard
`howdoi format date bash --link` -> gives a URL -> open URL

Essentially, I'll make a small logic block that checks to see if the result is a URL and, if so, it opens the browser. Otherwise you just get large type and the answer on the clipboard.

**Comment by vitorgalvao** [comment]
> `howdoi format date bash --link` -> gives a URL -> open URL

Giving a `--` option in Alfred is atypical. And parsing that would be more work than the idiomatic way of an [alternative action modifier](https://www.alfredapp.com/help/workflows/advanced/alternative-actions/). I.e. if you press ⌘↩ you open the link, if you ↩ you get the Large Type.

Updated the PR with that change.

[⤓ Updated Packaged Workflow ](https://github.com/gleitz/alfred-howdoi/files/10502625/Howdoi.alfredworkflow.zip)

**Comment by gleitz** [comment]
Thanks for the quick responses! Will give that a spin

**Comment by gleitz** [comment]
Wow! The alternative action modifier is amazing and works perfectly. I was also able to set the PATH and now my `howdoi` command is recognized.

One last idea - howdoi users are probably used to asking for multiple answers – for example adding `-n2` for two answers:

```
» howdoi create tar command line
tar cfJ <archive.tar.xz> <files>
```

and  
```
» howdoi create tar command line -n2
★  Answer from https://stackoverflow.com/questions/18855850/create-a-tar-xz-in-one-command ★
tar cfJ <archive.tar.xz> <files>

================================================================================

★  Answer from https://stackoverflow.com/questions/53283240/how-to-create-tar-file-with-7zip ★
tar cf - <source folder> | 7z a -si <Destination archive>.tar.7z
```

I noticed that with the incantation of `howdoi "${1}"` the flags like `-n2` don't seem to be recognized.
If I change this to `howdoi ${1}`, then the `-n2` is recognized properly.

Any thoughts on `"${1}"` vs `${1}` vs `{query}` (rather than argv)?

**Comment by vitorgalvao** [comment]
> I noticed that with the incantation of `howdoi "${1}"` the flags like `-n2` don't seem to be recognized.

Alfred isn’t a shell, the input should be assumed to be a single argument. By not quoting the variable, it could lead to unexpected behaviour. E.g. what if the question has a `-` as part of it but that unknowingly triggers a `howdoi` flag? It becomes unexpected behaviour.

Updated again. Now users can configure their preferred number of answers. 

[⤓ Updated Packaged Workflow](https://github.com/gleitz/alfred-howdoi/files/10503713/Howdoi.alfredworkflow.zip)

**Comment by gleitz** [comment]
Perhaps I'm getting too specific with requirements. People will usually want 1 answer. Sometimes they will want 2 (-n2). Sometimes they will want the whole answer rather than a code snippet (-a). Sometimes they want to save the answer (--save).

In those cases, perhaps we say that you should be using a shell, rather than Alfred.

Let's remove the number of answers, just keep the alternative action modifier, and then I'll merge this and update the Forum.

Thanks again for all your help!

**Comment by vitorgalvao** [comment]
Pushed reset to previous iteration.

**Pull request merged**
